-include Makefile.local

all:
	make -C src
#	make -C src/oacom
	make -C src/plugins
	
clean:
	make -C src clean
#	make -C src/oacom clean
	make -C src/plugins clean
	
install:
	make -C src install
#	make -C src/oacom install
	make -C src/plugins install

